-- =====================================================================
-- Migration 0004: IVR runtime tables used by the dynamic-greeting function
--
-- These two tables were previously hand-created through a Studio SQL
-- snippet (supabase/snippets/*.sql) and never committed as a migration, so
-- any fresh/reset environment had no `orders` or `ivr_logs` relation. The
-- edge function's PostgREST calls failed with PGRST205 ("Could not find the
-- table in the schema cache"), which is why the greeting always announced
-- the hardcoded fallback order id and no call was ever logged.
--
-- The snippet DDL also lacked the unique constraints the function relies on:
--   * orders.phone_number  -> `.maybeSingle()` lookup + snippet's ON CONFLICT
--   * ivr_logs.call_sid    -> `.upsert(..., { onConflict: "call_sid" })`
-- Without them the upsert would fail with 42P10 even once the tables existed.
-- =====================================================================

create table if not exists orders (
  id               bigint generated by default as identity primary key,
  phone_number     text not null,
  order_id         text not null,
  customer_name    text,
  delivery_address text,
  product_name     text,
  status           text not null default 'pending',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- For databases created before product_name was added.
alter table orders add column if not exists product_name text;

-- Required by the caller lookup and by the seed snippet's ON CONFLICT clause.
create unique index if not exists orders_phone_number_uidx
  on orders (phone_number);

-- The IVR resolves an order by id (carried through the call in Exotel's
-- CustomField), so that lookup must be unique and indexed.
create unique index if not exists orders_order_id_uidx
  on orders (order_id);

create table if not exists ivr_logs (
  id            bigint generated by default as identity primary key,
  call_sid      text not null,
  caller_number text,
  order_id      text,
  step          text,
  user_input    text,
  status        text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Required by `.upsert(..., { onConflict: "call_sid" })` in the edge function.
create unique index if not exists ivr_logs_call_sid_uidx
  on ivr_logs (call_sid);

create index if not exists ivr_logs_caller_number_idx
  on ivr_logs (caller_number);

-- =====================================================================
-- Row Level Security
-- The dynamic-greeting function talks to PostgREST with the service-role
-- key (server-to-server webhook, no end-user session), which bypasses RLS.
-- RLS is therefore enabled with no permissive policies so that the anon and
-- authenticated roles cannot read caller numbers or addresses.
-- =====================================================================
alter table orders    enable row level security;
alter table ivr_logs  enable row level security;

-- =====================================================================
-- Data API grants
-- `auto_expose_new_tables` is unset (see supabase/config.toml), which matches
-- the current cloud default: tables newly created in `public` are NOT reachable
-- through the Data API roles without an explicit GRANT. Without these the edge
-- function's PostgREST calls fail with 42501 "permission denied for table",
-- even using the service-role key (service_role bypasses RLS, not GRANTs).
-- Only service_role is granted; anon/authenticated stay locked out.
-- =====================================================================
grant select, insert, update on table orders   to service_role;
grant select, insert, update on table ivr_logs to service_role;
grant usage, select on sequence orders_id_seq   to service_role;
grant usage, select on sequence ivr_logs_id_seq to service_role;
