-- =====================================================================
-- Migration 0005: append-only per-step trace for IVR calls
--
-- `ivr_logs` has a unique index on call_sid and is written with
-- `upsert(..., { onConflict: "call_sid" })`, so it holds exactly one row per
-- call: the LATEST state. That is useful as a summary but makes it impossible
-- to see how a call progressed — each step overwrites the previous one, so a
-- flow that ran welcome -> address -> done is indistinguishable from one that
-- only ever reached `done`.
--
-- Diagnosing a misconfigured Exotel flow needs exactly that progression (a
-- flow stuck on its first applet logs `welcome` and nothing else), so each step
-- is also appended here. No unique constraint: one row per applet request.
-- =====================================================================

create table if not exists ivr_call_events (
  id          bigint generated by default as identity primary key,
  call_sid    text not null,
  step        text,
  user_input  text,
  status      text,
  -- Which applet Exotel appears to have called from, inferred from the request
  -- shape. Records when a request arrived with no `step` parameter, which is
  -- the signature of a Passthru applet (Passthru cannot play audio, so a flow
  -- relying on it for prompts produces a silent call).
  applet_hint text,
  created_at  timestamptz not null default now()
);

create index if not exists ivr_call_events_call_sid_idx
  on ivr_call_events (call_sid, created_at);

create index if not exists ivr_call_events_created_at_idx
  on ivr_call_events (created_at desc);

-- Same posture as orders/ivr_logs: service_role only, RLS on with no policies,
-- so anon and authenticated cannot read caller numbers or call traces.
alter table ivr_call_events enable row level security;

grant select, insert on table ivr_call_events to service_role;
grant usage, select on sequence ivr_call_events_id_seq to service_role;
