-- =====================================================================
-- Migration 0006: telephony-level call status tracking
--
-- `ivr_logs.status` already tracks the caller's furthest point in the IVR
-- conversation (WELCOME_SERVED, ORDER_CONFIRMED, ADDRESS_CONFIRMED, ...), set
-- by `dynamic-greeting`. There was no equivalent for the call itself:
-- ivr-engine could ask Exotel for a StatusCallback but nothing in this repo
-- ever received one, so a call's final telephony outcome (completed/failed/
-- busy/no-answer) was never recorded anywhere.
--
-- `call_status` / `ended_at` add that: set once by ivr-engine at call start
-- (`queued`) and finalized by the new `ivr-status-callback` function when
-- Exotel reports the call ended. `ivr_status_events` is the append-only
-- counterpart to `ivr_call_events` — every StatusCallback Exotel sends,
-- verbatim, independent of the summary row, so an unrecognised status is
-- still captured rather than silently dropped.
-- =====================================================================

alter table ivr_logs add column if not exists call_status text;
alter table ivr_logs add column if not exists ended_at timestamptz;

create table if not exists ivr_status_events (
  id          bigint generated by default as identity primary key,
  call_sid    text not null,
  status      text,
  event_type  text,
  raw         jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists ivr_status_events_call_sid_idx
  on ivr_status_events (call_sid, created_at);

-- Same posture as the other IVR tables: service_role only, RLS on with no
-- permissive policies, so anon/authenticated cannot read call metadata.
alter table ivr_status_events enable row level security;

grant select, insert on table ivr_status_events to service_role;
grant usage, select on sequence ivr_status_events_id_seq to service_role;
